# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Free Trial (3c8deffd-e61e-4cf4-a054-0414465da130)'
    backendAzureRmResourceGroupName: 'kumar'
    backendAzureRmStorageAccountName: 'strdemo'
    backendAzureRmContainerName: 'terraform'
    backendAzureRmKey: '$(tfstateFile)'

- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Free Trial (3c8deffd-e61e-4cf4-a054-0414465da130)'

- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'Free Trial (3c8deffd-e61e-4cf4-a054-0414465da130)'
